#!/usr/bin/env python3
"""prepare_oeis.py — OEIS submission packets for the new signed Erdős–Straus sequences.

REPORT §11 introduced the signed graded count of 4/n = 1/x+1/y+1/z over ℤ*: solutions are
graded by how many denominators are negative, (f̃₀, f̃₁, f̃₂, f̃₃)(n), with f̃₀ = the classical
positive count f(n). The repo notes f̃₁ and the even total F̃ = Σ_k f̃_k are not in OEIS
(checked 2026-06). This script writes ready-to-submit b-files + descriptions for:

  f̃₁(n)  — # solutions with exactly one negative denominator (col `f1` of the census)
  F̃(n)   — total signed count f̃₀+f̃₁+f̃₂ (an EVEN function on ℤ; REPORT §11.6)

from data/signed_census_1e4.csv (n = 2..10000, machine-validated by verify_signed.py).
Cross-references: A192787 (f̃₀ = f on x≤y≤z, the classical count). Output: data/oeis/.

Run:  python3 analysis/prepare_oeis.py
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, os.pardir, "data")
OUT = os.path.join(DATA, "oeis")


def load():
    rows = {}
    with open(os.path.join(DATA, "signed_census_1e4.csv")) as fh:
        r = csv.DictReader(fh)
        for row in r:
            n = int(row["n"])
            f0, f1, f2 = int(row["f0"]), int(row["f1"]), int(row["f2"])
            rows[n] = (f1, f0 + f1 + f2)          # (f̃₁, F̃)
    return rows


def write_bfile(path, seq, idx):
    """OEIS b-file: 'n a(n)' per line, over the data range."""
    with open(path, "w") as fh:
        for n in sorted(seq):
            fh.write(f"{n} {seq[n][idx]}\n")


def datasec(seq, idx, lo=2, count=30):
    ns = [n for n in sorted(seq) if n >= lo][:count]
    return ", ".join(str(seq[n][idx]) for n in ns)


if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    seq = load()
    write_bfile(os.path.join(OUT, "b_f1tilde.txt"), seq, 0)
    write_bfile(os.path.join(OUT, "b_Ftilde.txt"), seq, 1)
    # sanity vs the documented record prime
    assert seq[2521] == (377, 9 + 377 + 307), seq[2521]

    desc = f"""# OEIS submission packets — signed Erdős–Straus counts (REPORT §11)
# Generated by analysis/prepare_oeis.py from data/signed_census_1e4.csv (n=2..10000).
# Each is machine-validated (analysis/verify_signed.py); b-files in this directory.

## Sequence 1 — f̃₁(n): signed Erdős–Straus solutions with exactly one negative denominator

%S DATA: {datasec(seq, 0)}
NAME: Number of solutions of 4/n = 1/x + 1/y + 1/z in nonzero integers x<=y<=z (unordered,
      excluding trivial cancelling triples {{t,-t,n/4}}) with exactly one negative denominator.
OFFSET: 2
COMMENT: The grade-1 component of the signed graded count over Z* (REPORT §11). f̃₁(n)=0 iff
      n in {{2,4}}. Empirically rank-anticorrelated with the classical count f̃₀=A192787:
      corr(f̃₀,f̃₁) = -0.43 (the chirality see-saw); the "hard" Erdős–Straus primes (square
      classes mod 840) are the RICHEST in f̃₁. f̃₁(2521)=377 while f̃₀(2521)=9.
CROSSREF: A192787 (f̃₀, classical positive count, x<=y<=z).
KEYWORD: nonn
b-file: b_f1tilde.txt   (n=2..10000)

## Sequence 2 — F̃(n): total signed Erdős–Straus count (even function on Z)

%S DATA: {datasec(seq, 1)}
NAME: Total number of solutions of 4/n = 1/x + 1/y + 1/z in nonzero integers x<=y<=z
      (unordered, excluding trivial cancelling triples), over all sign patterns.
OFFSET: 2
COMMENT: F̃ = f̃₀+f̃₁+f̃₂+f̃₃ with f̃_k(-n)=f̃_{{3-k}}(n), so F̃ is EVEN on Z (REPORT §11.6).
      F̃(2)=1 is the unique "signless" point. The Erdős–Straus conjecture is the statement
      that the grade-0 part f̃₀ stays positive on the positive axis.
CROSSREF: A192787 (f̃₀).
KEYWORD: nonn
b-file: b_Ftilde.txt   (n=2..10000)
"""
    with open(os.path.join(OUT, "SUBMISSION.md"), "w") as fh:
        fh.write(desc)
    print(f"wrote {OUT}/b_f1tilde.txt, b_Ftilde.txt, SUBMISSION.md")
    print(f"  f̃₁: {datasec(seq, 0, count=12)} ...")
    print(f"  F̃ : {datasec(seq, 1, count=12)} ...")
    print(f"  check: f̃₁(2521)={seq[2521][0]}, F̃(2521)={seq[2521][1]}  (record prime)")
